#!/bin/bash
# Copyright (C) 2000-2020 Synology Inc. All rights reserved.

MakeClean='clean'

case "${MakeClean}" in
	[Yy][Ee][Ss])
		make clean
		;;
esac

#echo "make ${MAKE_FLAGS}"
#make "$MAKE_FLAGS"
make